name: PageSpeed Report

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  pagespeed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: Instalar dependências
        run: npm install

      - name: Gerar relatório PageSpeed
        run: npx ts-node scripts/generate-pagespeed.ts

      - name: Commit do relatório
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add PAGESPEED.md
          git commit -m "chore: update PageSpeed report" || echo "No changes"
          git push
